version: '3.8'

services:
  # Servicio para la base de datos PostgreSQL
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: task_manager_user
      POSTGRES_PASSWORD: secure_password46*/
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dvp_network

  # Servicio para la API de .NET
  api:
    build:
      context: ./TaskManagementAPI
      dockerfile: Dockerfile
    container_name: task-api
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres-db;Port=5432;Database=task_management_db;Username=task_manager_user;Password=secure_password46*/"
    depends_on:
      - postgres
    networks:
      - dvp_network

  # Servicio para la aplicación Angular
  angular:
    build:
      context: ./TaskManagementApp
      dockerfile: Dockerfile
    container_name: task-angular
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - dvp_network

networks:
  dvp_network:
    driver: bridge

volumes:
  pgdata:
